// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqoltvorxotanishrhzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxb2x0dm9yeG90YW5pc2hyaHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjA4OTYsImV4cCI6MjA2OTM5Njg5Nn0.t-cSHgHa54YqfRwlXDa9-OUK5oeV_rzqrBthGlF7g2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: false,
    autoRefreshToken: false,
  }
});

// Helper function to get current user from localStorage
export const getCurrentUser = () => {
  const sessionData = localStorage.getItem('user_session');
  if (sessionData) {
    try {
      const { user, timestamp } = JSON.parse(sessionData);
      // Verificar que la sesión no sea muy antigua (24 horas)
      if (Date.now() - timestamp < 24 * 60 * 60 * 1000 && user) {
        return user;
      } else {
        localStorage.removeItem('user_session');
        return null;
      }
    } catch (error) {
      localStorage.removeItem('user_session');
      return null;
    }
  }
  return null;
};