// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqoltvorxotanishrhzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxb2x0dm9yeG90YW5pc2hyaHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjA4OTYsImV4cCI6MjA2OTM5Njg5Nn0.t-cSHgHa54YqfRwlXDa9-OUK5oeV_rzqrBthGlF7g2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});